core/templates/404.html, core/templates/core/includes/footer.html, core/templates/core/includes/header.html, core/templates/core/includes/hero_landing_page.html, core/tests/test_mixins.py
also fixes header/footer path in 404 page, home link on header logo
=> Fix static image path in templates

conf/urls.py, contact/mixins.py, contact/tests/test_views.py, contact/views.py
https://uktrade.atlassian.net/browse/CMS-214
=> Update contact form success url

core/mixins.py, core/templates/core/industries_landing_page.html, core/templates/core/industry_page.html, core/templates/core/landing_page.html, core/templates/core/setup_guide_landing_page.html, core/templatetags/cms_tags.py, core/tests/test_mixins.py, core/tests/test_templatetags.py, core/views.py
https://uktrade.atlassian.net/browse/CMS-242
=> Only display child pages in current language

core/static/js/dit.js, core/static/js/main.js
https://uktrade.atlassian.net/browse/CMS-296
=> Fix header keyboard accessibility

core/templates/core/includes/labelled_card_grid.html, core/templates/core/includes/labelled_card_with_description_grid.html, core/templates/core/landing_page.html
https://uktrade.atlassian.net/browse/CMS-350
=> Use card with description for landing page industries

core/templates/core/industry_page.html
https://uktrade.atlassian.net/browse/CMS-357
=> Use cards with description in related industries section

core/templates/core/includes/footer.html
https://uktrade.atlassian.net/browse/CMS-420
=> Fix hardcoded links in footer

opportunities/templates/opportunities/high-potential-opportunities-form.html, opportunities/templates/opportunities/high-potential-opportunities-success.html, opportunities/templates/opportunities/high-potential-opportunity-detail.html
[this task](https://uktrade.atlassian.net/browse/TT-450)
=> Fix page meta title

opportunities/templates/opportunities/high-potential-opportunities-success.html, opportunities/templates/opportunities/high-potential-opportunity-detail.html
[this task](https://uktrade.atlassian.net/browse/TT-451)
=> Imporove accessibility of images on HPO page

opportunities/forms.py, opportunities/templates/opportunities/high-potential-opportunity-detail.html
[this task](https://uktrade.atlassian.net/browse/TT-470)
=> Replace HPO h1 elements with h2

.gitignore, conf/tests/test_redirects.py, conf/urls_redirect.py
https://uktrade.atlassian.net/browse/CMS-495
=> Add redirects for fair processing notice pages

core/static/js/dit.components.hideParagraphOnScroll.js, opportunities/templates/opportunities/high-potential-opportunity-detail.html
[this task](https://uktrade.atlassian.net/browse/TT-497)
=> Hide HPO contact paragraph on scroll

conf/urls.py, opportunities/tests/test_views.py, opportunities/views.py
[this task](https://uktrade.atlassian.net/browse/TT-511)
=> Seperate HPO success page

opportunities/forms.py, opportunities/tests/test_views.py, opportunities/views.py
[this task](https://uktrade.atlassian.net/browse/TT-879)
=> Fix HPO form submit

requirements.in, requirements.txt, requirements_test.txt
[this task](https://uktrade.atlassian.net/browse/TT-918)
=> Upgrade requests for security vulnerability fix

conf/settings.py, conf/urls.py, requirements.in, requirements.txt, requirements_test.txt
=> Upgrade healthcheck

conf/sitemaps.py, contact/mixins.py, contact/views.py, core/mixins.py, core/templates/core/base.html, core/templates/core/base_cms.html, core/tests/test_views.py, core/views.py
https://uktrade.atlassian.net/browse/CMS-496
=> Add localised urls in metadata

core/templates/core/landing_page.html
=> Fix lack of margin below banner on invest home page.

core/templates/core/includes/breadcrumbs.html, core/templates/core/includes/plain_card_grid.html, core/templates/core/industries_landing_page.html, core/templates/core/industry_page.html, core/templates/core/landing_page.html, core/templates/core/setup_guide_landing_page.html
This [ticket](https://uktrade.atlassian.net/browse/TT-1369)
I've added IDs to help with test automation & improve accessibility a bit
=> TT-1369 add IDs to important page elements

opportunities/forms.py, opportunities/tests/test_forms.py, opportunities/tests/test_views.py, opportunities/views.py
https://uktrade.atlassian.net/browse/XOT-819
=> HPO forms sending UTM data

core/templates/core/landing_page.html
This is to make automated testing more reliable & easier to maintain
=> TT-1369 add IDs to relevant page elements

core/templates/core/landing_page.html
Card only appears when title and text are specified with either option of feature flag
=> Fixed card showing up when feature flag off and nothing in cms

requirements.in, requirements.txt, requirements_test.txt
No changelog because it's a bugfix for a pre-release enhancement.
=> CI-145 Update invest header
